"""coluna admin agora é bool

Revision ID: 45508fda6cff
Revises: e9d0fe7ebe11
Create Date: 2025-08-14 19:12:57.554957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45508fda6cff'
down_revision = 'e9d0fe7ebe11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('admin',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=False,
               postgresql_using='admin::boolean')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('admin',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
