"""alteração na coluna de senha, onde agora pode se passar um valor nulo

Revision ID: 46672c298c13
Revises: 96fe5677f330
Create Date: 2025-08-13 17:48:27.733510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46672c298c13'
down_revision = '96fe5677f330'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)

    # ### end Alembic commands ###
