"""correção de migração

Revision ID: 4f6a0aeb0e5d
Revises: 9d151b71e85c
Create Date: 2025-08-25 18:38:27.132711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f6a0aeb0e5d'
down_revision = '9d151b71e85c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('priority_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'priority', ['priority_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('priority_id')

    # ### end Alembic commands ###
