"""alteração na coluna de acesso, onde agora a mesma se chama admin

Revision ID: ba6755c679b8
Revises: 46672c298c13
Create Date: 2025-08-13 18:00:19.196830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba6755c679b8'
down_revision = '46672c298c13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin', sa.Integer(), nullable=False))
        batch_op.drop_column('access_level')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('access_level', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_column('admin')

    # ### end Alembic commands ###
