"""adicionadas colunas de data de atribuíção e data de conclusão

Revision ID: c4402a3dee50
Revises: 4f6a0aeb0e5d
Create Date: 2025-08-27 19:15:43.263629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4402a3dee50'
down_revision = '4f6a0aeb0e5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('closed_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.drop_column('closed_at')
        batch_op.drop_column('assigned_at')

    # ### end Alembic commands ###
