"""Adiciona coluna de cor aos setores

Revision ID: cd7cb326fe02
Revises: eb7205e36b55
Create Date: 2025-08-19 19:44:22.026642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd7cb326fe02'
down_revision = 'eb7205e36b55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sector', schema=None) as batch_op:
        batch_op.add_column(sa.Column('color', sa.String(length=7), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sector', schema=None) as batch_op:
        batch_op.drop_column('color')

    # ### end Alembic commands ###
